### ISSUE TITLE
etcd based service announcement

### ISSUE THREAD

**Issue by superstructor** [joukou/joukou-docker-riak#14]

**Comment by tazjin** [comment]
I would love a generic way for this, e.g. a Docker image that you can run as `docker run -e "SERVICE=riak" -e "EXT_IF=ens32" --net="host" foo/etcd-announce` which then announces the `riak` service with the local hostname and the IP from the `ens32` interface.

I have this on my todo list, would that work for you as well?

**Comment by superstructor** [comment]
Yes that would be ideal. This is basically what I had in mind for the sidekick container, but I didn't think of making it generic. I'll create a new project for the Dockerfile now.

**Comment by superstructor** [comment]
In the process of getting the project up here: https://github.com/joukou/joukou-docker-etcd-announce

**Comment by tazjin** [comment]
My take on this, using a tiny scratch-based container with a static executable instead: https://github.com/tazjin/etcd-announcer && https://registry.hub.docker.com/u/tazjin/etcd-announcer/

**Comment by superstructor** [comment]
@tazjin thanks for etcd-announcer, that is more efficient and possibly more reliable.

I am looking at supporting a SkyDNS announcer instead of vanilla-etcd keys. SkyDNS can resolve DNS queries against etcd key/values. What do you think ?
