### ISSUE TITLE
Improve intra-cluster networking

### ISSUE THREAD

**Issue by superstructor** [joukou/joukou-docker-riak#7]
Currently Riak's intra-cluster communication ports are published to the host machine's network interface(s).

A better solution would be to use an overlay network such as [Rudder](https://coreos.com/blog/introducing-rudder/) to provide a networking layer between host machine's.

**Comment by tazjin** [comment]
I would like to mention that `--net="host"` works perfectly fine as well (if Riak would be the only service on a box requiring this that is)

**Comment by superstructor** [comment]
Indeed, I've also been using `--net="host"`.

I've found it mainly becomes an issue when trying to run multiple environments on the same cluster; e.g. production and staging Riak clusters.
