### ISSUE TITLE
Improve init of Riak

### ISSUE THREAD

**Issue by superstructor** [joukou/joukou-docker-riak#8]
I've tried several solutions
- systemd
  - requires --privileged or CAP_SYS_ADMIN (security issue)
  - stability issues
- supervisord (started via `riak console` or `riak start` then `riak attach`)
  - `riak` and `riak-admin` tools cannot connect to local node, even though it is started.
- direct instantiation w/ no init tool (started via `riak console` or `riak start` then `riak attach`)
  - `riak` and `riak-admin` tools cannot connect to local node, even though it is started.
- phusion baseimage w/ runit

This issue also relates to the [`quay.io/joukou/base`](https://github.com/joukou/joukou-docker-base) image, as that is where the init system is installed.

We need to chose an init system and resolve the associated issues that is
- stable
- handles appropriate signals
- preferably does not require special Docker privileges
- allows use of riak-admin and riak cli tools when entering via nsenter

**Comment by tazjin** [comment]
Hey!

So if I read this correctly you've so far mostly investigated running a supervision system inside the container - did you experience any problems with the direct instantiation except for your `riak-admin` connectivity issues?

Also do you have more information about those problems? It might be a configuration thing, because that works fine for me:

``` sh
~> docker run --name riak -td tazjin/riak
64d1399ac771a4cf97e34305e26c2b503d864d2cdc769e99dde17b175d0e5e16
~> sudo -i -u root denter riak
root@64d1399ac771:/# export PATH="/usr/sbin:/bin:${PATH}"
root@64d1399ac771:/# riak ping
pong
```

The `denter` command is just a simple wrapper around `nsenter`:

```
#!/bin/bash

if [[ -z "$1" ]]; then
    echo "Usage: denter <container-name>";
    echo "Might require super-user privileges";
    exit 1;
fi

DOCKER_PID=$(docker inspect --format "{{ .State.Pid }}" $1)
nsenter --target $DOCKER_PID --mount --uts --ipc --net --pid
```

The container here is an Ubuntu container based on `phusion/baseimage` with Riak Enterprise 2.0. I'll make a version of that container using opensource Riak as well and publish it.

Back on topic: IMHO the supervision should be handled outside of the container, so the options are either the supervision/init system starting Riak (e.g. `systemd` on CoreOS) or Docker itself using the `--restart` flag.

**Comment by superstructor** [comment]
I also use `nsenter`. 

```
$ riak ping
Node 'riak@103.18.59.164' not responding to pings.

$ ip addr show eth0
    inet 172.17.0.12/16 scope global eth0

$ curl 172.17.0.12:8098/ping
OK
```

Your right, connectivity is a configuration issue. I'll raise a new issue to keep this conversation focused and fix that in both repos ( this and https://github.com/joukou/joukou-docker-riak-config).

Thanks!

**Comment by superstructor** [comment]
Regarding init, take a look at [the fleet unit](https://github.com/joukou/joukou-docker-riak/blob/develop/riak%40.service#L22) to see how the container is started on CoreOS.

It uses [systemd-docker](https://github.com/ibuildthecloud/systemd-docker) which basically just moves all the Docker container processes into the systemd cgroup. This means that when a container fails, systemd on CoreOS should know about it.

I would also prefer the simplest reliable approach, and if direct instantiation can work I think we should do that.

**Comment by tazjin** [comment]
I wasn't aware of `systemd-docker` and all the related supervision problems when just using `docker run` in a unit. Thanks for linking to that!

In general though if this provides us with reliable supervision through systemd then I think it should be the way forward. Might be worthwhile to test this against Docker's own container restart mechanism as well.

**Comment by superstructor** [comment]
+1

Are you able to provide just the CMD and/or ENTRYPOINT, with any associated scripts that are called, for starting Riak directly in your Dockerfile please ? 

I tested with runit/my_init from the Phusion base image and it works fine, but with direct execution I get a 138 EXIT CODE without any logs.

**Comment by tazjin** [comment]
Have a look [here](https://github.com/tazjin/dockerfiles/tree/master/riak-base).

That's a quick cleaned up version using opensource Riak, haven't rewritten our READMEs for public consumption yet so it's just the raw files :)

**Comment by superstructor** [comment]
Awesome, thanks!

Just confirming your happy for some of this to be integrated into this repo under the Apache 2.0 license ?

**Comment by tazjin** [comment]
Yes. I'll add a LICENSE to my repo this evening as well.

**Comment by superstructor** [comment]
@tazjin https://github.com/joukou/joukou-docker-riak/blob/develop/bin/boot
