### ISSUE TITLE
Dynamic (re-)configuration with etcd and confd

### ISSUE THREAD

**Issue by superstructor** [joukou/joukou-docker-riak#9]
Currently configuration is generated once-off at startup from environment variables with the [`joukou-docker-riak-config`](https://github.com/joukou/joukou-docker-riak-config) Dockerfile project.

Using confd will provide a cleaner and more flexible solution.

**Comment by superstructor** [comment]
I can see two options...

**1. Riak and confd in single container**

carmstrong was good enough to refer me to how this is done in Deis: 

https://github.com/deis/deis/blob/master/controller/bin/boot#L76

The main process (bash script) loops indefinitely after spawning confd and other services in the background. This allows running multiple daemons without the overkill of an init system.

Potential upsides: 
- simpler; especially to issue the restart/reload configuration command

Potential downsides:
- Docker has no direct oversight of the confd OR the other service(s) running in the container, leaving process management up to us (or an init system).

**2. Riak and confd in two separate containers**

In theory, this would work by launching a [confd sidekick](https://coreos.com/docs/launching-containers/launching/launching-containers-fleet/#run-a-simple-sidekick) container.

The two containers would share the config file(s) via a common shared volume.

That leaves the question, how would confd issue the [`reload_cmd` or `check_cmd`](https://github.com/kelseyhightower/confd/blob/master/docs/template-resources.md) commands ? 

Potential upsides:
- More reliable process management, tighter control over system resources, healthier system

Potential downsides:
- More complex; especially for `reload_cmd` and `check_cmd`

**Comment by superstructor** [comment]
@tazjin thoughts ?

**Comment by tazjin** [comment]
@superstructor This is not a requirement for us. We template some variables into the configuration at container launch time (such as the nodename), but the rest is static and baked into the image (which is why the image I published earlier is called `riak-base`).

**Comment by superstructor** [comment]
@tazjin I think the best approach is to keep `/etc/riak` as a volume.

This is a clean separation of concerns that lets you use
- a static riak.conf on the host
- a static riak.conf from another container shared via a common volume
- a confd container with riak.conf shared via a common volume
- a one-pass generator container (e.g. joukou-docker-riak-config, which could just be a one-pass of confd)
  etc.
